package.json

Did not work with current typescript 1.5.0-beta.

Updated typescript dependency

---

index.ts
test/basic/expectedOutput/patch0/output.txt
test/declarationDeps/expectedOutput/output.txt
test/declarationWatch/expectedOutput/patch0/output.txt
test/errors/expectedOutput/output.txt
test/es3/expectedOutput/output.txt
test/es5/expectedOutput/output.txt
test/nolib/expectedOutput/output.txt
test/simpleDependency/expectedOutput/patch0/output.txt
test/tsconfigInvalid/expectedOutput/output.txt
test/tsconfigNotReadable/expectedOutput/output.txt
test/typeSystemWatch/expectedOutput/patch0/output.txt

Match the output pattern of 'tsc', for integration with VSCode.

Added compile error category and code to output

---

README.md
package.json

Update repository links to TypeStrong

---

test/run.js
test/tsconfigNotReadable-1.8/expectedOutput/output.txt
test/tsconfigNotReadable-1.8/tsconfig.json
test/tsconfigNotReadable-1.8/webpack.config.js

One of the tests relied on TS failing on a comment in tsconfig.json. This PR addresses that.
@blakeembrey

Update tests now that tsconfig.json allows comments

---

index.ts

Change all log messages to output to stderr

---

test/tsconfigInvalid/expectedOutput-1.9/output.txt

maybe if I do this I'll tempt @jbrantly back :smile:

minor fix to test

---

test/html-webpack-plugin/expectedOutput-1.6/output.txt
test/html-webpack-plugin/expectedOutput-1.7/output.txt
test/html-webpack-plugin/expectedOutput-1.8/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.8/output.txt
test/html-webpack-plugin/expectedOutput-1.9/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.9/output.txt
test/tsconfigInvalid/expectedOutput-1.9/output.txt

Fix html-webpack-plugin tests

---

CHANGELOG.md
UPGRADE.md
package.json

Readying the 0.9 release

---

test/comparison-tests/create-and-execute-test.js

By simply preventing done from being called multiple times.  I don't believe this is a meaningful error and so it should not fail the build.

Fix "Error: done() called multiple times" issue

---

README.md

To save people from the extreme effort of Googling for it 😉

Add link to typescript docs on .d.ts files

---

README.md

Old link: https://github.com/Microsoft/TypeScript/wiki/tsconfig.json
Updated link: http://www.typescriptlang.org/docs/handbook/tsconfig-json.html

Update tsconfig.json doc link

---

README.md
src/compilerSetup.ts
src/constants.ts
src/interfaces.ts
src/servicesHost.ts

general tidy up of constants and interfaces

document webpack 2 in the readme

---

CHANGELOG.md
package.json
src/after-compile.ts
src/compilerSetup.ts
src/constants.ts
src/index.ts
src/instances.ts
src/interfaces.ts
src/servicesHost.ts
src/typings/node/node.d.ts
src/typings/objectAssign/objectAssign.d.ts
src/utils.ts
src/watch-run.ts
test/comparison-tests/nodeModulesMeaningfulErrorWhenImportingTs/expectedOutput-2.0/output.txt
test/comparison-tests/nodeModulesMeaningfulErrorWhenImportingTs/expectedOutput-2.1/output.txt

new node type definitions
started documenting the codebase some more

minor perf optimisation for loaderoptions

---

examples/webpack2-gulp-react-flux-babel-karma/gulp/webpack.js
examples/webpack2-gulp-react-flux-babel-karma/karma.conf.js

Remove usage of LoaderOptions

---

examples/webpack2-react-cdn-simple/index.html
examples/webpack2-react-cdn-simple/package.json
examples/webpack2-react-cdn-simple/src/index.tsx
examples/webpack2-react-cdn-simple/tsconfig.json
examples/webpack2-react-cdn-simple/webpack.config.js

It took me a while of bumbling around before I managed to get a minimal webpack2 and ts-loader configuration building so I thought this patch might be helpful for others that are not interested in using babel or gulp.

Added a simple example using webpack2, react and JSX without using babel

---

test/comparison-tests/conditionalRequire/expectedOutput-2.2/bundle.js
test/comparison-tests/conditionalRequire/expectedOutput-2.2/output.txt
test/comparison-tests/run-tests.js

stop running 2.1 tests as part of test pack

regenerate test data for conditionalRequire

---

README.md
examples/webpack2-fork-ts-checker/package.json
examples/webpack2-fork-ts-checker/src/fileWithError.ts
examples/webpack2-fork-ts-checker/src/fileWithoutError.ts
examples/webpack2-fork-ts-checker/src/index.ts
examples/webpack2-fork-ts-checker/tsconfig.json
examples/webpack2-fork-ts-checker/webpack.config.js

As a response to [TypeStrong/ts-loader#537](https://github.com/TypeStrong/ts-loader/issues/537) - adds informations about fork-ts-checker-webpack-plugin and one example of usage.

Add fork-ts-checker-webpack-plugin info and examples

---

README.md

demonstrated usability with watchers such as webpack -w

demonstrate usability with watchers, such as webpack --watch

---

README.md

See #693 and [this comment](https://github.com/TypeStrong/ts-loader/issues/508#issuecomment-350563769).

Mention tsconfig-paths-webpack-plugin in readme. Fixes #693.

---

.npmignore
package.json
src/tsconfig.json

feat: generate ambient types from implementation

---

README.md

docs: declaration files behavior for `transpileOnly: true`

---

README.md

See https://github.com/TypeStrong/ts-loader/issues/815#issuecomment-424963443

Add note about TypeScript version compatibility to README

---

README.md

Just a very small change! One of your badges looks different from the rest so I fixed it.

Changed badge style to match others

---

README.md

Looks like you forgot to write this.

Update README.md (dependencies installation in devDependencies)

---

.npmignore
CHANGELOG.md
package.json

other artefacts sneaking in right now

don't publish anything but ts-loader

---

.travis.yml

Node 12 is out.
Let's run the compatibility build with it :)

add node12 to travis build

---

CHANGELOG.md
package.json

Will include 
https://github.com/TypeStrong/ts-loader/pull/1008
https://github.com/TypeStrong/ts-loader/pull/1003

Prepare for 6.1.1 release

---

README.md

Update minimum compiler version to 3.6.3 in Readme

Update minimum compiler version to 3.6.3

---

CHANGELOG.md
package.json
src/instances.ts
yarn.lock

adjusted `chalk` import/initialization to new major

chore(deps): upgrade most production deps

---

README.md

Add afterDeclarations to the getCustomTransformers in README to address https://github.com/TypeStrong/ts-loader/issues/1222

Add afterDeclarations to getCustomTransformers in README.md

---

test/comparison-tests/customTransformer/uppercaseStringLiteralTransformer.js
test/comparison-tests/customTransformerUsingPathString/uppercaseStringLiteralTransformer.js
test/execution-tests/loaderOptions/uppercaseStringLiteralTransformer.js

See https://github.com/microsoft/TypeScript/issues/53077

fix: createLiteral removed in 5.1 https://github.com/microsoft/TypeScript/issues/53077#issuecomment-1453846217
