README.md
index.ts
package.json

In my project, I run `webpack` from the shell, and expect its output to be valid json. Having this module log to the console breaks the json parsing. In another context, I am spawning a process that where running this causes a console log that breaks the TAP output. In both cases, I would like the ability to turn off the logging.
I thought about adding a test but it seems like it would be quite a bit of work, and I'm not sure it's a good ROI.
Thanks for making this module!

Adding an option to suppress log messages.

---

index.ts

Handle cases where the tsconfig makes tsc output declaration files by searching
for the correct file by extension instead of assuming order of output files.

Handle declaration

---

index.ts

When using the transpileOnly option, the "special handling" code block for ES6 is skipped, preventing to target ES6 when using this option.

Fix for ES6 with transpileOnly option

---

LICENSE
README.md

This simplifies the license in the README and transfers the copyright over to TypeStrong. I want it to be more of a community project (that was the point of the transfer, right?) so I feel this is a necessary step. IANAL but I think I can do this.
cc @basarat @blakeembrey

Simplify license and update to TypeStrong

---

README.md
index.ts
package.json
test/ignoreDiagnostics/app.ts
test/ignoreDiagnostics/expectedOutput/bundle.js
test/ignoreDiagnostics/expectedOutput/output.transpiled.txt
test/ignoreDiagnostics/expectedOutput/output.txt
test/ignoreDiagnostics/webpack.config.js
typings/arrify/arrify.d.ts

This implements #60 
Note that there is an API change from typescript-simple-loader which named this option `ignoreWarnings`. I've opted for `ignoreDiagnostics` since it's more agnostic to warnings vs errors, but certainly open to feedback.
I shamelessly ripped some code from typescript-simple-loader for this. The basic idea is that I've added `loaderOptions` to the `instance` object (and made a partially hydrated `instance` object available earlier in the process). Then I changed the `formatErrors` function to take an instance object instead of the TypeScript compiler. This allows access to both the compiler and the ignoreWarnings option.
There was also some cleanup (as a separate commit) to help distinguish between loader options and compiler options in the code.
cc @blakeembrey …

ignoreDiagnostics feature

---

.travis.yml
README.md
index.ts
test/run.js
test/tsconfigInvalid-1.8/expectedOutput/output.txt
test/tsconfigInvalid-1.8/tsconfig.json
test/tsconfigInvalid-1.8/webpack.config.js

Finish removing support for 1.5.3 and 1.6 beta

---

index.ts

Tests were failing for typescript@next saying that `lib.es6.d.ts` could not be found. The problem was that `getDefaultLibFileName` should be returning the full path to the default lib and not just the file name.
@blakeembrey

Fix "`lib.es6.d.ts` could not be found"

---

index.ts
test/es6resolveParent/expectedOutput/bundle.js
test/es6resolveParent/expectedOutput/output.txt
test/es6resolveParent/index.tsx
test/es6resolveParent/submodule/index.tsx
test/es6resolveParent/tsconfig.json
test/es6resolveParent/webpack.config.js
test/issue92/app.ts
test/issue92/expectedOutput/bundle.js
test/issue92/expectedOutput/output.txt
test/issue92/submodule/submodule.tsx
test/issue92/tsconfig.json
test/issue92/webpack.config.js

This addresses #92. webpack resolution was not working correctly.
From that issue:
> So I've looked into this a bit and there are multiple cascading issues. The first issue is that there is a bug in ts-loader where the webpack lookup was failing (ts-loader first tries to resolve a file using webpack's resolution strategy). Since that was failing, the loader fell back on TypeScript's module resolution strategy. In this case TypeScript was unable to find the .tsx file because the `jsx` option was not specified in the compiler options, so that failed as well resulting in the "cannot find module" message. However, if you switched `moduleResolution` to `node` then TypeScript magically decided to include .tsx files in its lookup. Kind of weird if you ask me and possibly a bug that .tsx …

Fix bug with webpack resolution

---

.gitignore
index.ts
package.json
test/declarationOutput/app.ts
test/declarationOutput/expectedOutput-1.6/app.d.ts
test/declarationOutput/expectedOutput-1.6/bundle.js
test/declarationOutput/expectedOutput-1.6/output.txt
test/declarationOutput/expectedOutput-1.6/sub/dep.d.ts
test/declarationOutput/expectedOutput-1.7/app.d.ts
test/declarationOutput/expectedOutput-1.7/bundle.js
test/declarationOutput/expectedOutput-1.7/output.txt
test/declarationOutput/expectedOutput-1.7/sub/dep.d.ts
test/declarationOutput/expectedOutput-1.8/app.d.ts
test/declarationOutput/expectedOutput-1.8/bundle.js
test/declarationOutput/expectedOutput-1.8/output.txt
test/declarationOutput/expectedOutput-1.8/sub/dep.d.ts
test/declarationOutput/sub/dep.ts
test/run.js

This adds support for emitting `.d.ts` files when `declaration: true` is set in tsconfig. This brings ts-loader closer in-line with `tsc` behavior and allows other tools to possibly re-package the individual `.d.ts` files into a single one (outside the scope of this project, for now).
The test runner also had a minor update to support working with output in subdirectories.
This fixes #48.

Add support for emitting declaration files

---

index.ts
test/es6withCJS/app.ts
test/es6withCJS/expectedOutput-1.6/output.txt
test/es6withCJS/expectedOutput-1.7/bundle.js
test/es6withCJS/expectedOutput-1.7/output.txt
test/es6withCJS/expectedOutput-1.8/bundle.js
test/es6withCJS/expectedOutput-1.8/output.txt
test/es6withCJS/tsconfig.json
test/es6withCJS/webpack.config.js
test/ignoreDiagnostics/expectedOutput-1.8/output.txt

This PR cleans up module defaults and target handling and fixes #111 and #132
Previously the module output was defaulted to CommonJS except in the case where the target was set to ES6, in which case the module output was forced to "None". This worked well in TS 1.6 but causes problems in TS 1.7+ because it's impossible to configure ts-loader to `target: es6` and `module: commonjs`.
The new behavior is as follows:
- Default to CommonJS ONLY if `target` is **NOT** `es6`. This is a breaking change, but causes ts-loader to behave a little more like `tsc` (in that if you specify a `target: es6` but not module the output is es6 modules) and also will eventually provide a better default experience when webpack2 hits.
- If using TS 1.6, revert to the old behavior of forcing `module: none` if …

Don't force module output when targeting ES6

---

index.ts
package.json
test/npmLink/app.ts
test/npmLink/expectedOutput-1.6/bundle.js
test/npmLink/expectedOutput-1.6/output.txt
test/npmLink/expectedOutput-1.7/bundle.js
test/npmLink/expectedOutput-1.7/output.txt
test/npmLink/expectedOutput-1.8/bundle.js
test/npmLink/expectedOutput-1.8/output.txt
test/npmLink/tsconfig.json
test/npmLink/webpack.config.js
test/run.js
test/testLib/foo.ts
test/testLib/package.json

This fixes #134 by no longer using `getScriptSnapshot` in the ModuleResolutionHost. The issue with `getScriptSnapshot` is that it adds found files to the program cache which can cause discrepancies between the real path of the module and the symlink (webpack returns the real path, typescript finds and returns the symlink).

Fix support for `npm link`ing dependencies

---

index.ts
test/tsconfigInvalidFile/expectedOutput-1.6/bundle.transpiled.js
test/tsconfigInvalidFile/expectedOutput-1.6/output.transpiled.txt
test/tsconfigInvalidFile/expectedOutput-1.6/output.txt
test/tsconfigInvalidFile/expectedOutput-1.7/bundle.transpiled.js
test/tsconfigInvalidFile/expectedOutput-1.7/output.transpiled.txt
test/tsconfigInvalidFile/expectedOutput-1.7/output.txt
test/tsconfigInvalidFile/expectedOutput-1.8/bundle.transpiled.js
test/tsconfigInvalidFile/expectedOutput-1.8/output.transpiled.txt
test/tsconfigInvalidFile/expectedOutput-1.8/output.txt
test/tsconfigInvalidFile/tsconfig.json
test/tsconfigInvalidFile/webpack.config.js

Hey @jbrantly 
This PR is to mitigate the problems of https://github.com/TypeStrong/ts-loader/issues/117 - invalid files in `tsconfig.json` will be very obvious as a result of the change to error message.  Hope you like it; happy to tweak further.  I've added a test as well.

Make invalid files in tsconfig.json super obvious when ts-loader errors

---

index.ts
package.json
test/html-webpack-plugin/app.ts
test/html-webpack-plugin/expectedOutput-1.6/bundle.js
test/html-webpack-plugin/expectedOutput-1.6/index.html
test/html-webpack-plugin/expectedOutput-1.6/output.txt
test/html-webpack-plugin/expectedOutput-1.7/bundle.js
test/html-webpack-plugin/expectedOutput-1.7/index.html
test/html-webpack-plugin/expectedOutput-1.7/output.txt
test/html-webpack-plugin/expectedOutput-1.8/bundle.js
test/html-webpack-plugin/expectedOutput-1.8/bundle.transpiled.js
test/html-webpack-plugin/expectedOutput-1.8/index.html
test/html-webpack-plugin/expectedOutput-1.8/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.8/output.txt
test/html-webpack-plugin/expectedOutput-1.9/bundle.js
test/html-webpack-plugin/expectedOutput-1.9/bundle.transpiled.js
test/html-webpack-plugin/expectedOutput-1.9/index.html
test/html-webpack-plugin/expectedOutput-1.9/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.9/output.txt
test/html-webpack-plugin/index.html
test/html-webpack-plugin/tsconfig.json
test/html-webpack-plugin/webpack.config.js

Fix issue with html-webpack-plugin (#152)

---

README.md

Added docs as suggested here: https://github.com/TypeStrong/ts-loader/issues/108

Update README.md to include fail build details

---

index.ts

tackles the missing d.ts files for interface objects in typescript. closes #174

fix for declaration output to include d.ts files for interfaces

---

package.json
test/html-webpack-plugin/expectedOutput-1.6/output.txt
test/html-webpack-plugin/expectedOutput-1.7/output.txt
test/html-webpack-plugin/expectedOutput-1.8/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.8/output.txt
test/html-webpack-plugin/expectedOutput-1.9/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.9/output.txt

Also udated associated test results to reflect incremented lodash version.  This should fix 2 of the webpack tests that have been failing for a while.  The ^ meant that the version used was always the latest and when it changed the tests broke.  This will likely happen again at some point by the way; but I guess that's intentional?

update html-webpack-plugin to latest version to fix 2 tests

---

package.json
test/html-webpack-plugin/expectedOutput-1.6/index.html
test/html-webpack-plugin/expectedOutput-1.6/output.txt
test/html-webpack-plugin/expectedOutput-1.7/index.html
test/html-webpack-plugin/expectedOutput-1.7/output.txt
test/html-webpack-plugin/expectedOutput-1.8/index.html
test/html-webpack-plugin/expectedOutput-1.8/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.8/output.txt
test/html-webpack-plugin/expectedOutput-1.9/index.html
test/html-webpack-plugin/expectedOutput-1.9/output.transpiled.txt
test/html-webpack-plugin/expectedOutput-1.9/output.txt

they now require `type="text/javascript" ` in the output...

Fix some html-weback-plugin tests

---

index.ts

Uses watching.compiler.fileTimestamps which is set directly in
the compiler. See https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L105.
Fixes the https://github.com/TypeStrong/ts-loader/issues/155
when using the webpack.OldNodeWatchFileSystem.

Declarations update independent of compiler.watchFileSystem

---

index.ts

Node 6+ enforces the parameter to path.dirname to be a string (https://github.com/nodejs/node/commit/08085c49b6e49ecfffd638c6cd46f4de639ae4f4). The empty string results in the previous behavior.

Make ts-loader compatible with node v6

---

test/run.js

I realised that the tests were failing because there is no expected output.  I made the tests check at the beginning if there is an output to assert against and fail immediately if not.  I hope this makes the test pack faster and the reason for failure more obvious.
We should probably get rid of the 1.9 expected output by the way; there is no TS 1.9 and will not be.  We should likely adjust the build matrices to remove typescript@next since we don't have valid output for that either.

Fail fast if expectedOutput does not exist

---

CONTRIBUTING.md
test/run.js

fail fast conflicts with this at present.  Also allow the ability to run
a single test with `npm test -- --save-output --single-test testname`

All regeneration of test data when it doesn't already exist

---

index.ts

This is intended as a fix for issue #185 - a full explanation of what the problem was can be found in [this comment](https://github.com/TypeStrong/ts-loader/issues/185#issuecomment-222118959), but what it boiled down to is that the language service returns absolute paths for generated declaration files, and these were being used directly as keys in `compilation.assets`, causing Webpack to hang during the emit stage. Resolving the path relative to the current working directory beforehand fixes this issue. According to @t246246's comment on the issue, this only affects Windows, but as I don't have access to a Linux or OSX device, I can't confirm that.
One caveat to this fix is that the output file structure for the declaration files follows that of the source code - i.e, if the source looks …

Use a relative path for the declaration assets

---

index.ts

`instance.dependencyGraph` gets created using a raw `containingFile` value:
```ts
var servicesHost = {
// ...
resolveModuleNames: (moduleNames: string[], containingFile: string) => {
// ...
instance.dependencyGraph[containingFile] = ...
// ...
}
// ...
}
```
But is later accessed with a normalized path:
```ts
function loader(contents) {
// ...
var filePath = path.normalize(this.resourcePath);
// ...
let additionalDependencies = instance.dependencyGraph[filePath];
// ...
}
```
This breaks every scenario where `path.normalize` is not identity.
For example, in Windows, you get:
```
containingFile: 'C:/project/dir/file.ts'
path.normalize(containingFile): 'C:\\project\\dir\\file.ts'
```

Normalize dependency graph paths - Fix broken dependencies on Windows

---

index.ts

Reverting [old change](https://github.com/TypeStrong/ts-loader/pull/167) which has broken webpack hot module reloading. Issue #321

Rollback of "watch-run" logic

---

test/comparison-tests/create-and-execute-test.js
test/comparison-tests/importsWatch/app.ts
test/comparison-tests/importsWatch/expectedOutput-2.0/bundle.js
test/comparison-tests/importsWatch/expectedOutput-2.0/output.txt
test/comparison-tests/importsWatch/expectedOutput-2.0/patch0/bundle.js
test/comparison-tests/importsWatch/expectedOutput-2.0/patch0/output.txt
test/comparison-tests/importsWatch/expectedOutput-2.0/patch1/bundle.js
test/comparison-tests/importsWatch/expectedOutput-2.0/patch1/output.txt
test/comparison-tests/importsWatch/foo.ts
test/comparison-tests/importsWatch/patch0/foo.ts
test/comparison-tests/importsWatch/patch1/foo.ts
test/comparison-tests/importsWatch/tsconfig.json
test/comparison-tests/importsWatch/webpack.config.js

ie https://github.com/TypeStrong/ts-loader/pull/168

create importsWatch test based on @jbrantly's PR

---

index.ts

This let's the loader survive whenever the watched declaration file gets removed.

Use readFile for declarations

---

package.json
src/index.ts
src/instances.ts
src/interfaces.ts
src/servicesHost.ts
src/utils.ts
test/comparison-tests/vue/component.vue
test/comparison-tests/vue/expectedOutput-2.0/bundle.js
test/comparison-tests/vue/expectedOutput-2.0/bundle.transpiled.js
test/comparison-tests/vue/expectedOutput-2.0/output.transpiled.txt
test/comparison-tests/vue/expectedOutput-2.0/output.txt
test/comparison-tests/vue/helper.ts
test/comparison-tests/vue/index.vue
test/comparison-tests/vue/tsconfig.json
test/comparison-tests/vue/webpack.config.js

~Tests need more handling. Vue loader will produces absolute file path that is path dependent.
And it even produce hash that is machine specific! How can I handle these cases?~
Added _flaky mark to vue's test

[RFC] fix #270, support `appendTsSuffixTo` config

---

README.md

Sorry for the delay, get quite busy these days.

add documentation for appendTsSuffixTo

---

CHANGELOG.md
src/after-compile.ts
src/interfaces.ts
src/utils.ts
test/comparison-tests/aliasResolution/tsconfig.json
test/comparison-tests/babel-es6resolveParent/tsconfig.json
test/comparison-tests/babel-issue81/tsconfig.json
test/comparison-tests/babel-issue92/tsconfig.json
test/comparison-tests/declarationOutput/tsconfig.json
test/comparison-tests/html-webpack-plugin/tsconfig.json
test/comparison-tests/instance/tsconfig.json
test/comparison-tests/issue71/tsconfig.json
test/comparison-tests/large/tsconfig.json
test/comparison-tests/noErrorsPlugin/tsconfig.json
test/comparison-tests/nodeResolution/tsconfig.json
test/comparison-tests/vue/tsconfig.json

micro-optimisation for appendTsSuffixIfMatch function
#358

prevent adding/removing files crashes - fixes #358

---

src/servicesHost.ts
test/comparison-tests/issue372/app.ts
test/comparison-tests/issue372/expectedOutput-2.0/bundle.js
test/comparison-tests/issue372/expectedOutput-2.0/output.txt
test/comparison-tests/issue372/expectedOutput-2.0/patch0/bundle.js
test/comparison-tests/issue372/expectedOutput-2.0/patch0/output.txt
test/comparison-tests/issue372/expectedOutput-2.1/bundle.js
test/comparison-tests/issue372/expectedOutput-2.1/output.txt
test/comparison-tests/issue372/expectedOutput-2.1/patch0/bundle.js
test/comparison-tests/issue372/expectedOutput-2.1/patch0/output.txt
test/comparison-tests/issue372/foo.ts
test/comparison-tests/issue372/node_modules/@types/a/index.d.ts
test/comparison-tests/issue372/node_modules/@types/a/package.json
test/comparison-tests/issue372/node_modules/a/index.js
test/comparison-tests/issue372/node_modules/a/package.json
test/comparison-tests/issue372/patch0/app.ts
test/comparison-tests/issue372/tsconfig.json
test/comparison-tests/issue372/webpack.config.js

Normalizes paths returned by TS module resolution to fix duplicate dependency issue #372 on Windows.

Fix TS module resolution paths on Windows

---

src/servicesHost.ts

https://github.com/TypeStrong/ts-loader/issues/379
Made change to `servicesHost.ts`.  Raising PR now to trigger CI builds and see which tests are failing - will address those failures in a later commit.

typescript.sys should be compiler.sys

---

README.md
src/instances.ts

When ts-loader checks the `allowJs` flag of your tsconfig, it should be checking the fully loaded config, including all "extend"ed tsconfig files.
I also fixed a spelling mistake in the README that I noticed while working.

Fix bug when "extend"ing a tsconfig that specifies "allowJs"

---

test/comparison-tests/create-and-execute-test.js

which are to be expected between Windows and Linux due to line endings.
related to https://github.com/TypeStrong/ts-loader/pull/444 cc @herschel666

Make comparison tests tolerant to byte differences in output files

---

src/interfaces.ts
src/watch-run.ts
test/comparison-tests/issue441/app.ts
test/comparison-tests/issue441/expectedOutput-2.0/bundle.js
test/comparison-tests/issue441/expectedOutput-2.0/output.txt
test/comparison-tests/issue441/expectedOutput-2.0/patch0/bundle.js
test/comparison-tests/issue441/expectedOutput-2.0/patch0/output.txt
test/comparison-tests/issue441/expectedOutput-2.0/patch1/bundle.js
test/comparison-tests/issue441/expectedOutput-2.0/patch1/output.txt
test/comparison-tests/issue441/expectedOutput-2.1/bundle.js
test/comparison-tests/issue441/expectedOutput-2.1/output.txt
test/comparison-tests/issue441/expectedOutput-2.1/patch0/bundle.js
test/comparison-tests/issue441/expectedOutput-2.1/patch0/output.txt
test/comparison-tests/issue441/expectedOutput-2.1/patch1/bundle.js
test/comparison-tests/issue441/expectedOutput-2.1/patch1/output.txt
test/comparison-tests/issue441/foo.ts
test/comparison-tests/issue441/patch0/styles.d.ts
test/comparison-tests/issue441/patch1/styles.d.ts
test/comparison-tests/issue441/styles.d.ts
test/comparison-tests/issue441/tsconfig.json
test/comparison-tests/issue441/webpack.config.js

This fixes the bug described in issue TypeStrong/ts-loader/issues/441.

Add support for IgnoringWatchFileSystem-instance in watcher

---

src/interfaces.ts
src/watch-run.ts

Fixes #479. A bit better than #480 #481?

Fix watchpack breaking API

---

README.md

Updated for latest webpack syntax. leaving off the '-loader' throws an error

fix webpack example to include '-loader'

---

src/after-compile.ts
src/constants.ts

Report errors in JS(X) files when CheckJS is enabled

---

CHANGELOG.md
src/interfaces.ts
src/watch-run.ts

Use compiler.fileTimestamps cause watcher may be null

---

src/index.ts

fix https://github.com/TypeStrong/ts-loader/issues/597

fix(tsconfig): stop pass rootDir option to TypeScript compiler

---

README.md

Update documentation for creating output declaration (.d.ts) file and mark webpack-fail-plugin as no longer needed

Add documentation #599 #600

---

src/config.ts

If configFileName is a full filepath, findConfigFile return nothing.
Modify configFileName to fix windows compatibility.
Closes #604

Fix findConfigFile in Windows

---

src/config.ts
src/index.ts
src/instances.ts
src/interfaces.ts

This deprecates the `configFileName` option and renames it to `configFile`.
It keeps its user-facing behaviour, improving some path resolutions under the hood.
Using the `configFileName` option will now raise a `logWarning` in the console.

Add `configFile` option

---

package.json
src/servicesHost.ts
test/comparison-tests/localTsImplementationOfTypings/app.ts
test/comparison-tests/localTsImplementationOfTypings/expectedOutput-2.4/bundle.js
test/comparison-tests/localTsImplementationOfTypings/expectedOutput-2.4/output.txt
test/comparison-tests/localTsImplementationOfTypings/fake.ts
test/comparison-tests/localTsImplementationOfTypings/tsconfig.json
test/comparison-tests/localTsImplementationOfTypings/webpack.config.js

Fixes #620 by only reusing Typscript's isExternalLibraryImport designation if the loader-resolved module is a JS file and not a TS file.
Added a comparison-test rather than an execution-test as this really is just a question of "does it compile" rather than changing any behavior related to the generated JS.
Note that this also locks typescript down to 2.4.2 because right now building from a clean clone fails. Since typescript is currently ^2.4.0 it upgraded locally to the latest - 2.5.2 - and since 2.5.x updates some general typings (in this case System.readFile) that causes a build failure in config.ts. Not sure how you guys want to deal with that - it seemed outside the scope of my change to fix that but it did look fairly simple.
Please let me know what you're thinking!
-Will

Add an additional check for js files before reusing isExternalLibaryImport (#620)

---

src/servicesHost.ts

Fix none-node_module imports of built ts files

---

README.md

Looks like this was missed in #643.

Fix default logLevel in README

---

examples/react-babel-allowjs/.babelrc
examples/react-babel-allowjs/README.md
examples/react-babel-allowjs/index.html
examples/react-babel-allowjs/package-lock.json
examples/react-babel-allowjs/package.json
examples/react-babel-allowjs/src/App.js
examples/react-babel-allowjs/src/main.tsx
examples/react-babel-allowjs/tsconfig.json
examples/react-babel-allowjs/webpack.config.js

This is an example more tailored towards people who are using allowJs in mixed codebases where a migration to TypeScript is underway.
I also decided to keep testing and production setups outside of this as other examples cover that well and I often find it a bit confusing that some examples try to showcase so much stuff at once that if you're looking to solve a particular issue it can be hard to tell which specific settings are related to that issue.

Add babel/react/allowjs example

---

src/after-compile.ts
src/index.ts
src/instances.ts
src/interfaces.ts
src/servicesHost.ts
src/utils.ts
src/watch-run.ts

This works with the changes of Microsoft/TypeScript#20234

Using the new watch api of compiler

---

src/index.ts
src/instances.ts
src/servicesHost.ts

With this the error reporting happens correctly.

Fixes to support builder api for compiling https://github.com/johnnyreilly/typescript-ts-loader-watch-api-illustration correctly

---

README.md

Documents and fixes #732
Just a small note that if your `tsconfig.json` is outside of your project (root), TypeScript behaves weird and throws errors, if you don't also set the `context` to the project root.

Add note in docs about external config files

---

src/servicesHost.ts

Fix name collision in experimentalWatchApi code

---

examples/react-hot-boilerplate/package.json

With the [upgrade to Webpack 4](https://github.com/TypeStrong/ts-loader/commit/c122c9ffbf24eca99ef9297e9241d6176542010d), passing `NODE_ENV` is no longer necessary, and neither  is the `cross-env` dependency. 
Removing `cross-env` as suggested in https://github.com/TypeStrong/ts-loader/commit/c122c9ffbf24eca99ef9297e9241d6176542010d#r27961370.

Remove cross-env from react-hot-boilerplate

---

src/index.ts
src/instances.ts
src/interfaces.ts

TypeScript cant tell if there is invalidation because of custom module resolution, that means it needs to create new program whenver asked for
Fixes #746

Do not create program multiple times when there are no changes in files

---

README.md
examples/fork-ts-checker/webpack.config.js

Add a tip about suppressing "export not found" warnings for transpileOnly: true

---

src/interfaces.ts
src/utils.ts

This PR adds the `context` variable to the `ErrorInfo` interface. The primary use case is here is to allow custom error formatters to recover the full path to the file in which an error occurred, since I wanted to read the file from disk to use `'babel-code-frame'` to go along with the message.
I couldn't find tests that exercise `errorFormatter` functionality, but I'm happy to write some extras if you'd like.

Pass `context' to error formatters

---

README.md
examples/hot-module-replacement/README.md
examples/hot-module-replacement/package-lock.json
examples/hot-module-replacement/package.json
examples/hot-module-replacement/src/exports-string.ts
examples/hot-module-replacement/src/index.ts
examples/hot-module-replacement/webpack.config.js

Documenting HMR findings through https://github.com/TypeStrong/ts-loader/issues/761
I found another inconsistency with HMR compared to vanilla webpack, and have documented it in the example's README:
> You must re-require the hot replaced module
I'd probably call it a bug because it's still inconsistent with the way HMR works in vanilla webpack, but HMR is still achievable using `ts-loader`. Anyone else have opinions on this behavior?

Add minimal HMR example

---

package.json
src/interfaces.ts
src/servicesHost.ts
test/comparison-tests/npmLink/tsconfig.json
test/execution-tests/issue768/package.json
test/execution-tests/issue768/shrinkwrap.yaml
test/execution-tests/issue768/src/index.ts
test/execution-tests/issue768/tsconfig.json
test/execution-tests/issue768/webpack.config.js
test/execution-tests/run-tests.js
yarn.lock

* Add `realpath` to `moduleResolutionHost` so that TypeScript could follow symlink as it supposed to be
* Now that typescript follow symlink, npmLink test fails in 2.8.1 due to Microsoft/TypeScript#12358, fixed by modifying tsconfig file. (Also related to #773)
* Created a new test to cover this scenario.
Fix #768

Fix dependency resolution when using pnpm

---

src/index.ts
src/interfaces.ts
test/execution-tests/optionsCaching/foo.ts
test/execution-tests/optionsCaching/foo.vue
test/execution-tests/optionsCaching/tsconfig.json
test/execution-tests/optionsCaching/webpack.config.js

This is a bug we discovered in latest Vue CLI 3 beta (ref: https://github.com/vuejs/vue-cli/issues/1399).
When the webpack config contains multiple rules that use `ts-loader` but with different options, the current option caching implementation will incorrectly always use the cached options from the first matched rule. This is because the caching is done by using only the webpack instance + the `instance` option as the key - it's not taking multiple rules into account.
This PR fixes it by ensuring each webpack instance + ts instance combo gets its own cache which caches validated options using a WeakMap.
The added test would fail without this fix as the options in the second rule will be ignored and `appendTsxSuffixTo` will take no effect.

Fix options caching when ts-loader is used in multiple rules

---

src/index.ts

this tweaks https://github.com/TypeStrong/ts-loader/pull/788 by exposing proper public types API from root index.d.ts so consumer doesn't have to traverse private package path to access interfaces.
**before**
```js
// @ts-check
const tsLoaderOptionsRules = /** @type {import('ts-loader/dist/types/interfaces').LoaderOptions}*/ ({
configFile: tsConfig,
transpileOnly: true
})
```
**after**
```js
// @ts-check
const tsLoaderOptionsRules = /** @type {import('ts-loader').Options}*/ ({
configFile: tsConfig,
transpileOnly: true
})
```

fix(types): expose public interfaces from root index.d.ts

---

src/after-compile.ts
src/constants.ts
src/index.ts
src/instances.ts
src/watch-run.ts
test/comparison-tests/create-and-execute-test.js
test/comparison-tests/declarationOutputWithMaps/app.ts
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/app.d.ts
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/app.d.ts.map
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/bundle.js
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/output.txt
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/sub/dep.d.ts
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/sub/dep.d.ts.map
test/comparison-tests/declarationOutputWithMaps/sub/dep.ts
test/comparison-tests/declarationOutputWithMaps/tsconfig.json
test/comparison-tests/declarationOutputWithMaps/webpack.config.js

@johnnyreilly: Please check this out and let me know if you want any changes or if I did something wrong creating the tests.
Fix for https://github.com/TypeStrong/ts-loader/issues/820

Added support for TypeScript declaration map

---

CHANGELOG.md
package.json
src/after-compile.ts
src/interfaces.ts
test/comparison-tests/declarationOutput/expectedOutput-3.0/output.txt
test/comparison-tests/declarationOutput/tsconfig.json
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/app.d.ts.map
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/output.txt
test/comparison-tests/declarationOutputWithMaps/expectedOutput-3.0/sub/dep.d.ts.map
test/comparison-tests/declarationOutputWithMaps/tsconfig.json

In regards of: https://github.com/TypeStrong/ts-loader/issues/190
I'll try to explain the fix:
Below is the code where we prepare the relative path for the d.ts files so we can add them to Webpack's compilation assets. 
```
const assetPath = path.relative(
compilation.compiler.context,
declarationFile.name
);
compilation.assets[assetPath] = {
source: () => declarationFile.text,
size: () => declarationFile.text.length
};
```
**Example**
Project root: /home/user/jon/projects/a/
[webpack.main]: index.ts
[webpack.output.path]: /home/user/jon/projects/a/dist/
[compilerOptions.declarationDir]: ./dist/typings/
[Scope variables]
[compilation.compiler.context]: /home/user/jon/projects/a/
[compilation.compiler.outputPath]: /home/user/jon/projects/a/dist/
[Other]
All relative assets in …

Fixed issue with incorrect output path for declaration files

---

CHANGELOG.md
package.json

> `ts-loader` currently relies on the hoisting in order to have access to the `typescript` package
> It causes issues with package trees that do not support hoisting, such as Yarn Plug'n'Play.
Should fix #839 😃

Lists typescript as a peer dependency

---

README.md

Hey Developers!
I am a new user to ts-loader. While reading through the documentation I found two minor errors where syntax are not properly highlighted. 
Patrick

Fix minor errors on syntax highlighting in README.md

---

CHANGELOG.md
package.json
src/utils.ts
test/comparison-tests/projectReferencesRootDir/app.ts
test/comparison-tests/projectReferencesRootDir/expectedOutput-3.1/bundle.js
test/comparison-tests/projectReferencesRootDir/expectedOutput-3.1/output.txt
test/comparison-tests/projectReferencesRootDir/lib/out/index.d.ts
test/comparison-tests/projectReferencesRootDir/lib/out/index.js
test/comparison-tests/projectReferencesRootDir/lib/src/index.ts
test/comparison-tests/projectReferencesRootDir/lib/tsconfig.json
test/comparison-tests/projectReferencesRootDir/tsconfig.json
test/comparison-tests/projectReferencesRootDir/webpack.config.js

`rootDir` inside a referenced project’s config wasn’t being considered in figuring out where the output JS files for the project will be, a.k.a. why https://github.com/Microsoft/TypeScript/issues/26410 should still be a thing 🙂 
Fixes #868

Fix projectReferences with rootDir

---

CHANGELOG.md
README.md
package.json
src/instances.ts
src/interfaces.ts
test/comparison-tests/customTransformer/webpack.config.js
test/comparison-tests/customTransformerUsingPathString/customerTransformers.js

A lot of transformers requires a Program instance so we pass ts.Program to getCustomTransformers() to be able to pass it on to transformers. Transformers mostly need ts.Program in order to access the type checker.
Fixes #860

Pass ts.Program to getCustomTransformers()

---

.github/main.workflow

PR for @mcolyer to illustrate filtering issue with GitHub Actions.  See https://github.com/TypeStrong/ts-loader/pull/898
Note the `check for new tag` step.  It's ending with neural as a new tag is not being published.  Ideally subsequent steps would also be marked as neutral but alas instead they get marked as failed.

example of filter issue for @mcolyer

---

examples/fast-incremental-builds/README.md

Really just a small typo fix 🙃Thank you for your work.

fixed name of fork-ts-checker-webpack-plugin

---

CHANGELOG.md
examples/react-babel-karma-gulp/yarn.lock
examples/thread-loader/yarn.lock
package.json
src/after-compile.ts
src/compilerSetup.ts
src/config.ts
src/constants.ts
src/index.ts
src/instances.ts
src/interfaces.ts
src/logger.ts
src/resolver.ts
src/servicesHost.ts
src/utils.ts
src/watch-run.ts
test/execution-tests/option-context/yarn.lock
yarn.lock

Some tidy up of the internals to use the `@types/webpack` webpack package for webpack specific typings. 
As far as I can see there are two bugs in the webpack typings which I'll try and upstream: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35053

internal: remove usage of hand crafted webpack typings

---

.gitignore
.npmignore
.vscode/launch.json
CONTRIBUTING.md
src/tsconfig.json
test/comparison-tests/README.md
test/comparison-tests/run-tests.js
test/execution-tests/README.md
test/execution-tests/run-tests.js

- Turns on source maps (excludes them from files published to npm)
- Adds `--debug` switch to run-tests.js in execution-tests and comparison-tests
- Adds configurations for VS Code to debug the currently open execution test or comparison test
- Updates docs accordingly
It's a miracle, @johnnyreilly, it even works on Windows 😛 
<details>
<summary>Proof that source maps are excluded from npm:</summary>
```
$ npm pack
npm notice 
npm notice 📦  ts-loader@6.0.0
npm notice === Tarball Contents === 
npm notice 2.8kB  package.json                 
npm notice 23.3kB CHANGELOG.md                 
npm notice 879B   HISTORY.md                   
npm notice 57B    index.js                     
npm notice 1.1kB  LICENSE                      
npm notice 31.1kB README.md                    
npm notice …
```

Improve debugging experience

---

CHANGELOG.md
package.json
src/servicesHost.ts

Fixes #934 
Fixes #919 
There was really no way to know this without debugging, but getting default typeRoots for a project doesn't work if the module resolution host doesn't implement `getCurrentDirectory()`. Arguably the language service API shouldn’t treat it as optional, or should emit a warning if it’s missing, or fall back to the default from `ts.sys` (maybe I'll bring this up to Sheetal, but it certainly wouldn't land until 3.6), but I think a good policy for ts-loader would be to implement _all_ members of any kind of Host, especially if it’s as easy a just including things from `ts.sys`. It _is_ kind of misleading because there are other places (I think `CompilerHost` is an example) where missing optional members get filled in with good defaults.

Fix type reference directive resolution

---

CHANGELOG.md
src/after-compile.ts

Fix missing error output in root project with project references

---

CHANGELOG.md
package.json
src/servicesHost.ts
yarn.lock

Latest version typescript has more strict type check.

Upgrade typescript version

---

CHANGELOG.md
package.json
src/index.ts
src/instances.ts
src/interfaces.ts

This is a minimal fix for #943.
When a new root file is processed, ensure that the instance version is increased. 
It is an alternative to the bigger PR #945.

Fix: Increase the instance version when new root files are found

---

README.md

This fixes #902. It removes the dead example links and changes the wording to express that hot module replacement is not really supported by ts-loader.

Correct Hot Module replacement description

---

test/comparison-tests/conditionalRequire/README.md
test/execution-tests/README.md

See also https://github.com/TypeStrong/ts-loader/pull/908#issuecomment-514103428

Fix broken links in `test/` readme files

---

README.md

These missing examples were removed in PR #899.
See also https://github.com/TypeStrong/ts-loader/pull/908#issuecomment-514103428

Remove links to missing examples about HappyPack

---

examples/vanilla/webpack.config.js

The webpack-dev-server uses the root path not the dist folder, so a specific output folder config is needed for the yarn watch command to work.

Add output path to vanilla example webpack config

---

src/after-compile.ts
test/comparison-tests/allowJs-ts-check/expectedOutput-3.6/bundle.js
test/comparison-tests/allowJs-ts-check/expectedOutput-3.6/output.transpiled.txt
test/comparison-tests/allowJs-ts-check/expectedOutput-3.6/output.txt
test/comparison-tests/allowJs-ts-check/src/error1.js
test/comparison-tests/allowJs-ts-check/src/error2.js
test/comparison-tests/allowJs-ts-check/src/index.js
test/comparison-tests/allowJs-ts-check/tsconfig.json
test/comparison-tests/allowJs-ts-check/webpack.config.js

fix: no errors reported if flagged with @ts-check

---

src/instances.ts

it seems that ts-loader is  trying to emit declaration files for a declaration file, this causes typescript's getOutputDeclarationFileName throw an error

fixes https://github.com/TypeStrong/ts-loader/issues/1014

---

CHANGELOG.md
package.json
src/after-compile.ts
src/instances.ts
test/comparison-tests/run-tests.js
test/execution-tests/run-tests.js
test/run-tests.js

Added apis from microsoft/TypeScript#33503
Also added --match-test to run tests matched by regexp passed in

Consume typescript apis from typescript nightly

---

CHANGELOG.md
package.json
src/tsconfig.json

This PR sets the type declaration output directory to be the same as the JS output directory so that types are automatically pulled in for folks who are requiring things from `dist`.
I’ve been spelunking around in the internals of `ts-loader` to see how I can get access to the compiler/checker. I’ve had to use a `yarn link`’d copy of `ts-loader` with the change contained in this PR because types aren’t matching up for files in `dist`. 
While I was at it, I enabled declaration maps too.
Current (hella nasty) workaround:
```typescript
const { getTypeScriptInstance } = require('ts-loader/dist/instances') as typeof import('ts-loader/dist/types/instances');
const tsLoader = require('ts-loader') as typeof import('ts-loader/dist/types/index');
```

Output types alongside JS files, enable declaration maps

---

README.md

This PR resolves a few tasks from #1024, namely:
- moving the "Installation" and "Running" sections higher up in `README`
- homogenizing the use of "ts-loader" in `README`

Reorganize README & Homogenize use of "ts-loader"

---

README.md
examples/thread-loader/package.json
examples/thread-loader/webpack.config.js

`checkSyntacticErrors` option is not available anymore. We are supposed to use diagnosticOptions now (see https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/477)
This PR updates README and thread-loader example accordingly.

Change README and examples from obsolete checkSyntacticErrors to syntactic diagnostic option

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.dockerignore
.gitignore
.npmignore
.travis.yml
Dockerfile
appveyor.yml
test/execution-tests/pnpm/pnpm-lock.yaml

Provide a [devcontainer](https://code.visualstudio.com/docs/remote/containers) for ts-loader to make it easier for people to get up and running contributing.  
Also should allow for [codespaces](https://github.com/features/codespaces/) support when access is unlocked.

devcontainer for ts-loader

---

CHANGELOG.md
appveyor.yml
package.json
src/after-compile.ts
src/instances.ts
src/interfaces.ts

This PR should remove some of webpack deprecation warnings.

Fix webpack deprecations (fix #1126)

---

.github/workflows/release.yml

The changes of https://github.com/TypeStrong/ts-loader/pull/1144 have broken it

Fix release mechanism

---

CHANGELOG.md
README.md
package.json
src/index.ts
src/interfaces.ts
src/utils.ts

Fix the issue when I use both `lang="tsx"` and `lang="ts"` in vue single file components.
For `lang="ts"`: 
```
{
appendTsSuffixTo: [/\.vue$/],
transpileOnly: true,
}
```
For `lang="tsx"`: 
```
{
appendTsxSuffixTo: [/\.vue$/],
transpileOnly: true,
}
```
They get the same hash because `getOptionsHash` use only values for hashing.
So for tsx vue file, it reuses the loader options which is only for ts vue, which add `.ts` suffix not `.tsx`.
That can lead to wrong compilation result.

Fix getOptionsHash when two options has different props but same values.

---

README.md

Make it clear in the docs that transpileOnly does not affect the way project references are built.

Update docs to show transpileOnly does not affect project references

---

CHANGELOG.md
package.json
src/index.ts
src/instances.ts

Fixed https://github.com/TypeStrong/ts-loader/issues/1194

Fixed deprecation warnings on webpack@5.

---

CHANGELOG.md
package.json
src/instances.ts

This fixes the deprecation warning in webpack 5 as discussed in issue #[1196](https://github.com/TypeStrong/ts-loader/issues/1196). Writing assets such as declarations is moved to the afterProcessAssets hook of the compilation from the afterCompile hook of the compiler.
As the afterProcessAssets hook does not exist in webpack 4 to make ts-loader work for both webpack 4 and 5 it is necessary to execute different code depending on whether afterProcessAssets exists.  This means that the new code is not tested at all by either the execution or comparison tests, which feels wrong.  I'm not sure how to fix this until tests using webpack 5 are introduced, which feels like a major task.
I have tested this build with a small project using webpack 4 and webpack 5.  If I introduce a deliberate error …

Replace afterCompile to stop webpack 5 warning

---

README.md

This fixes broken tables.
before
after

doc: escape pipe in table

---

CHANGELOG.md
package.json
src/index.ts
src/instances.ts

Closes https://github.com/TypeStrong/ts-loader/issues/1203
This PR should fix a memory leak issue when using multiple webpack instances that get discarded over time.
I initially converted the `webpackInstances` array to a WeakMap (plus a global index) but that wasn't enough to fix the leak, since the cached `TSInstance` held in `instances.ts` was still retaining the webpack compiler and never being freed.
In the end, I removed the webpack instance array and changed the TS instance cache by using a combined WeakMap + Map so that we maintain the same behaviour but keep the lifetime of `TSInstance`s tied to the webpack compiler that spawned them.
There is one small change in how `loaderOptions.instance` names are generated: 
- old names: `0_default_e3b0c44298fc1c14`
- new names: …

Fix memory leak when using multiple webpack instances

---

CHANGELOG.md
package.json
src/instance-cache.ts
src/instances.ts

Possible fix for https://github.com/TypeStrong/ts-loader/issues/1206
When using `thread-loader`, the `loader._compiler` field is `undefined`, this causes a runtime error when trying to use it as a key in a WeakMap.
This PR changes the instance cache so that it now uses a dummy "marker" object as reference when the compiler instance is undefined.

Fix failed builds when using thread-loader

---

CHANGELOG.md
package.json
src/after-compile.ts
src/instances.ts

The fix in [PR1200](https://github.com/TypeStrong/ts-loader/pull/1200) was made to prevent deprecation warnings with webpack5, because it is no longer allowed to add assets during the afterCompile hook.  These functions were moved to the new afterProcessAssets hook in webpack5.  It seems that in watch mode, the afterProcessAssets hook is not called, so if any errors are introduced they will not be reported to webpack.
This PR allows the makeAfterCompile function to select whether assets should be added and/or errors should be reported.  Running under webpack4 the behaviour is unchanged.  Under webpack5 assets are added during afterProcessAssets and errors are reported during afterCompile.  This should correct the behaviour observed in …

Fixed missing errors in watch mode in webpack5

---

CHANGELOG.md
package.json

Desc: should explicitly indicate peer/optional dependency for yarn v2.
Reproducing bug: https://github.com/aicest/webpack-v5-demo

Add peer dependencies for Yarn PnP

---

CHANGELOG.md
package.json
src/servicesHost.ts

This ensures that there is no unnecesary watcher invoked resulting in full config file reloads and builds

Instead of checking date, check time thats more accurate to see if something has changed

---

README.md

Setting this option on projects with lots of files can reduce compilation time. Case-insensitivty requires normalization of file paths, which involves executing regex's. This shows up in the hot path of compilation profiling.
Switching to case sensitive file names skips the normalization step and increases build speed by ~5%  (closed-source project, sorry)

Add documentation for the useCaseSensitiveFileNames option

---

CHANGELOG.md
package.json
src/instances.ts

This greatly reduces the time needed to resolve FilePathKey objects on watch builds. (~20% from 20s to 16s)
Note: The only case where I could see this optimization performing poorly is if a symlink was changed between builds, but I don't believe webpack handles that gracefully anyways.
Relates to #1215
See the performance traces below:
Before:
After:

Add a cache to file path mapping

---

CHANGELOG.md
README.md
package.json
src/instances.ts

See https://github.com/TypeStrong/ts-loader/issues/1243 for discussion of problem and this fix.

Update definition files in watch mode in webpack@5

---

CHANGELOG.md
README.md
package.json
src/after-compile.ts
src/instances.ts

See: https://github.com/TypeStrong/ts-loader/issues/1204
Originally, declaration file and errors were emitted during the compiler.afterCompile hook. In webpack5 it is no longer allowed to emit assets in the afterCompile hook so I moved this to the compilation.afterProcessAssets hook. But then as reported here errors were not emitted in watch mode. So I made the change here which is to emit errors during the compiler.afterCompile hook but to emit declaration files in the loader._compilation.afterProcessAssets hook.
But then it was reported that declaration files are not emitted in subsequent runs during watch mode. This was traced to loader._compilation not being persistent so we need to use a compilation hook to get the compilation so we can add the afterProcessAssets hook. With …

Re-fix Webpack 5 watch not failing on error

---

README.md

The latest webpack WatchIgnorePlugin has updated syntax that expects an options object
https://webpack.js.org/plugins/watch-ignore-plugin/

Update README.md for latest webpack 5 syntax

---

CHANGELOG.md
package.json
src/servicesHost.ts

Instead of looking up filePathKey twice, cache in in the local scope. This isn't a hugely expensive lookup path, but is a hot path on large project recompiles (especially after caches are blown away). Profiling shows that even the Map lookup shows non-trivial cache lookup aggregate time. (Less than a non-cached implementation though :) )

Optimize fileExists callback path

---

.travis.yml
README.md

It's been flaky for a while and it seems to be stopping unlimited support for OSS.  We have GitHub Actions so let's roll with that.

Drop Travis

---

CHANGELOG.md
package.json
src/after-compile.ts
src/compilerSetup.ts
src/config.ts
src/index.ts
src/instances.ts
src/interfaces.ts
src/servicesHost.ts
src/utils.ts

In some deployment systems, the builder and source code are placed in different paths, and we also expect the typescript's version to be completely controlled by the user, if the builder does not depend on `typescript`, then we will get error containing `cannot found "typescript"` caused by the top-level typescript import statement at `ts-loader`, In other words, **_we SHOULD respect the resolved compiler_**.
Prior to TypeScript 3.8, you can import a type using import. With TypeScript 3.8, you can import a type using the import statement, or using `import type`, and import type is always guaranteed to be removed from your JavaScript, this project has stopped testing TypeScript 3.6 and 3.7 at [953358e](https://github.com/TypeStrong/ts-loader/commit/953358eb1b090dd9add0824c4746220b0ebe56c1), …

feat: remove top-level typescript import statements

---

CHANGELOG.md
package.json
src/index.ts
src/typings/loaderUtils/loaderUtils.d.ts
yarn.lock

Remove usage of loader-utils:
https://github.com/TypeStrong/ts-loader/pull/1286#issuecomment-823264246

fix: Removed usage of loader-utils

---

CHANGELOG.md
package.json
src/after-compile.ts

When using webpack devserver I often get an Unhandled promise rejection when a file is removed (generally because I switch to another git branch)
I get UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fileName' of undefined
at provideErrorsToWebpack (after-compile.js:128:29)
(I assume it may also happen while simply using watch mode)
Without the provided fix, I need to stop and restart the devserver to solve the problem

UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fileName' of undefined

---

CHANGELOG.md
package.json
src/index.ts
test/comparison-tests/loaderOptionsCaching/app.ts
test/comparison-tests/loaderOptionsCaching/expectedOutput-4.1/bundle.js
test/comparison-tests/loaderOptionsCaching/expectedOutput-4.1/output.txt
test/comparison-tests/loaderOptionsCaching/expectedOutput-transpile-4.1/bundle.js
test/comparison-tests/loaderOptionsCaching/expectedOutput-transpile-4.1/output.txt
test/comparison-tests/loaderOptionsCaching/submodule-es5/index.ts
test/comparison-tests/loaderOptionsCaching/submodule-es5/tsconfig.json
test/comparison-tests/loaderOptionsCaching/submodule-es6/index.ts
test/comparison-tests/loaderOptionsCaching/submodule-es6/tsconfig.json
test/comparison-tests/loaderOptionsCaching/tsconfig.json
test/comparison-tests/loaderOptionsCaching/webpack.config.js

Backport "Fixed impossibility to have several instances of ts-loader with different compiler options" #1317 to v8

Backport #1287 to v8 (#1291)

---

CHANGELOG.md
package.json

I added the minimum webpack version in the peerDependencies section of package.json.
See also #1323

Add webpack minimum version in peerDependencies

---

CHANGELOG.md
package.json
src/instances.ts

The error message here was misleading, it wasn't reporting on the same variable that it checks in line 360. If ts-loader was configured with a `getCustomTransformers` function that returned a module path which didn't had a `module.exports = function(){..}` in it, the error message displayed was the following: `... should export a function, got function`.

getCustomTransformers error message fix

---

CHANGELOG.md
examples/vanilla/package.json
examples/vanilla/yarn.lock
package.json
src/index.ts
yarn.lock

Fixes #1345 by ensuring that `configPath` is set to the default value if `undefined` is supplied.
There's some prettier reformatting in this that makes the PR a little noisier - but this effectively comes down to a 2 line change.

fix: undefined configPath now falls back to default

---

CHANGELOG.md
README.md
package.json
src/instances.ts
src/interfaces.ts

Add function to get the latest program

---

README.md

Fix wrong devtool example (#1362)

---

.gitattributes

It makes TypeScript become the top language.

Chore: disable GitHub Linguist detection for tests files

---

.github/workflows/push.yml
.github/workflows/release.yml
CHANGELOG.md
package.json
src/interfaces.ts
src/servicesHost.ts

Speculative fix for #1421 - based on @cspotcode's `ts-node` work here: https://github.com/TypeStrong/ts-node/pull/1648
This has been tested on https://github.com/mjbvz/ts-47-webpack-error mentioned by @mjbvz here: https://github.com/microsoft/TypeScript/issues/48020
Using the initial `git clone` of the test repo, it errors out as expected:
```shell
john@john-XPS-13-9343  ~/code/github/ts-47-webpack-error   main  yarn
yarn install v1.22.5
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages... …
```

cater for change in resolveTypeReferenceDirective API in TypeScript 4.7

---

CHANGELOG.md
package.json
src/watch-run.ts

Fixes Error when running ts-loader with webpack 5 : "times is not iterable"
closes #1438

Bug fix: support webpack 5 in ts-loader

---

.github/workflows/push.yml
CHANGELOG.md
package.json
src/instances.ts
src/interfaces.ts
src/servicesHost.ts
yarn.lock

fix: cater for change in resolveTypeReferenceDirective API in TypeScript 4.7

fix: cater for change in resolveTypeReferenceDirective API in 4.7

---

CHANGELOG.md
package.json

Follow on after https://github.com/TypeStrong/ts-loader/pull/1446

Make v9 latest following v8 release

---

.vscode/extensions.json
.vscode/settings.json

for making the VSCode environment stable so that the `format document` will keep the code style as expected.

chore: add vscode extension settings

---

CONTRIBUTING.md
REFERENCES.md

Just a few typo fix to get my hand wet. 🌷

docs: misc update

---

README.md

docs: clarify Declarations (.d.ts) section in the README

---

CHANGELOG.md
package.json
src/resolver.ts
test/comparison-tests/aliasResolution/expectedOutput-4.8/output.txt
test/comparison-tests/aliasResolution/expectedOutput-4.8/patch0/output.txt
test/comparison-tests/errorFormatter/expectedOutput-4.8/output.txt
test/comparison-tests/localTsImplementationOfTypings/expectedOutput-4.8/output.txt

As discussed in #1503, #1505 and #1504, `enhanced-resolve` causes issues in case both `typescript` and `enhanced-resolve` are able to resolve a module specifier.
Changes made in this PR will disable `enhanced-resolve`. This change might be reverted once a proper workflow has been worked out.
In doing so, this PR will fix #1505 and fix #1504.
This is a follow-up to PR #1503 which introduced the changes causing these issues.

Hotfix: Disable `enhanced-resolve`

---

README.md

Adding missing comma in the webpack.config.js example file in the README.md

Add missing comma in README.md

---

README.md

The existing link points to a plugin that is many years old and does not work with modern versions of webpack. This updated fork works with webpack 5.

docs: update link to DeclarationBundlerPlugin in Declarations (.d.ts) section in the README

---

CHANGELOG.md
package.json
src/compilerSetup.ts

Make `ts-loader` obey the user's preferred value for the `skipLibCheck` option

Make skipLibCheck overridable

---

CHANGELOG.md
package.json
src/index.ts

Fixes https://github.com/TypeStrong/ts-loader/issues/1638

fix: inputSourceMap can be null

---

CHANGELOG.md
package.json
src/instances.ts
src/servicesHost.ts

Small change and make error messages more detailed.

fix: add more detailed error messages
